name: Cortex CLI Code Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CORTEX_API_KEY: ${{ secrets.CORTEX_API_KEY }}
  CORTEX_API_KEY_ID: ${{ secrets.CORTEX_API_KEY_ID }}
  CORTEX_API_URL: https://api-viso-8vocygkchsephm7mczadnc.xdr-qa2-uat.us.paloaltonetworks.com
  MIN_LOG_LEVEL: DEBUG

jobs:
  cortex-code-scan:
    runs-on: ubuntu-latest
    container:
      image: cimg/node:22.17.0
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python 3 and pip
        run: |
          apt update
          apt install -y python3 python3-pip python3-venv

      - name: Check Versions
        run: |
          node -v
          python3 --version
          pip3 --version

      - name: Download cortexcli
        run: |
          set -x
          crtx_resp=$(curl "$CORTEX_API_URL/public_api/v1/unified-cli/releases/download-link?os=linux&architecture=amd64" \
            -H "x-xdr-auth-id: $CORTEX_API_KEY_ID" \
            -H "Authorization: ${CORTEX_API_KEY}")
          crtx_url=$(echo $crtx_resp | jq -r ".signed_url")
          curl -o cortexcli $crtx_url
          chmod +x cortexcli
          ./cortexcli --version

      - name: Run Cortex CLI Code Scan
        run: |
          ./cortexcli \
            --api-base-url "${CORTEX_API_URL}" \
            --api-key "${CORTEX_API_KEY}" \
            --api-key-id "${CORTEX_API_KEY_ID}" \
            code scan \
            --directory "$(pwd)" \
            --repo-id "${{ github.repository }}" \
            --branch "${{ github.ref_name }}" \
            --source "GITHUB_ACTIONS" \
            --upload-mode "no-upload" \
            --framework "sca" \
            --create-repo-if-missing
